name: unit testing for the solarsytem project
on:  
  push:

env:
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}

jobs:   
  build:
    strategy:
      matrix:
        node-version: [18,19,20]
        os: [ubuntu-latest,windows-latest]
        exclude:
          - node-version: 18
            os: windows-latest
        include:
          - node-version: 18
            os: ubuntu-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4.2.2
        
      - name: Setup the nodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}

      - name: cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules-${{hashfiles('package-lock.json')}}

      - name: install dependencies
        run: npm install
        
      - name: Testing the file
        run: npm test

  code-coverage:
    container: 
      image: node:18
    #services:
     # mongo-db:
      #  image: vallabha051/mongodb-db:latest
    #env: 
     # MONGO_URI: 'mongodb://localhost:27017/superData'
      #MONGO_USERNAME: non-prod-user
      #MONGO_PASSWORD: non-prod-password
    runs-on: ubuntu-latest
    steps:
      - name: run the code-coverage
        continue-on-error: true
        run: npm run coverage

      - name: Archive the Test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: Test-Results.xml

  dev-deploy:
    needs: [build,code-coverage]
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repository
        uses: actions/checkout@v4.2.2
      
      - name: kubectl install
        uses: azure/setup-kubectl@v3
        with: 
          version: 'v1.26.0'  

